### ISSUE TITLE
Not an issue, but for general information

### ISSUE THREAD

**Issue by chinnichaitanya** [VineyS/python_discord_logger_rewrite#1]
Hi there @VineyS! Trust you are doing well. I'm the author of the original [`discord-logger`](https://pypi.org/project/discord-logger/) package. Very much appreciate you developing this and giving me credits. 🙂

I'm also happy to inform that the [latest release of discord-logger (v1.2.2)](https://pypi.org/project/discord-logger/) now has an option to disable sending hostname in messages. 😃

I believe the true spirit of open-source culture is collaborative development. On this note, I do have a request. If you or other developers have any feature requests or modifications, I encourage raising issues [here in the original repository](https://github.com/chinnichaitanya/python-discord-logger/issues) or even better, submit PRs! 😃
It would not be ideal to release a new package for every feature.  This way, the overall community would get benefitted and developers could also avoid the confusion on deciding which package to use.

Thank you once again! 😃
Go open-source! 🚀

**Comment by VineyS** [comment]
Aight Mate. Thanks :) 

Since you updated it to a new version, i'll be removing this rewritten module from Pypi and as you mentioned, for feature updates, i'll be submitting an issue or I would make one and PR it.

Regards,
Viney
